/**
 * this files conatis Types of Actions that we used in Redux
 */

//Clinet Sorting
export const SORT_BY_SIZE_CLIENT_ASC = "SORT_BY_SIZE_CLIENT_ASC";
export const SORT_BY_SIZE_CLIENT_DESC = "SORT_BY_SIZE_CLIENT_DESC";
export const SORT_BY_PRICE_CLIENT_ASC = "SORT_BY_PRICE_CLIENT_ASC";
export const SORT_BY_PRICE_CLIENT_DESC = "SORT_BY_PRICE_CLIENT_DESC";
export const SORT_BY_ID_CLIENT_ASC = "SORT_BY_ID_CLIENT_ASC";
export const SORT_BY_ID_CLIENT_DESC = "SORT_BY_ID_CLIENT_DESC";
export const SORT_BY_NO_SORT = "SORT_BY_NO_SORT";
//Server Sorting
export const SORT_BY_SIZE_SERVER = "SORT_BY_SIZE_SERVER";
export const SORT_BY_PRICE_SERVER = "SORT_BY_PRICE_SERVER";
export const SORT_BY_ID_SERVER = "SORT_BY_ID_SERVER";
export const RESET_SORT_BY_SERVER = "RESET_SORT_BY_SERVER";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";

//Server Limit Products
export const SET_LIMIT_PRODUCTS = "SET_LIMIT_PRODUCTS";

export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const PRODUCTS_ACTIVE_IN_ACTIVES = "PRODUCTS_ACTIVE_IN_ACTIVES";
export const PRODUCTS_END_OF_PRODUCTS = "PRODUCTS_END_OF_PRODUCTS";
export const PRODUCTS_SET_BATCH = "PRODUCTS_SET_BATCH";
export const PRODUCTS_ADD_BATCH = "PRODUCTS_ADD_BATCH";

export const SET_PAGINATION_PAGE_NUMBER = "SET_PAGINATION_PAGE_NUMBER";
export const INCREASE_PAGINATION_PAGE_NUMBER =
  "INCREASE_PAGINATION_PAGE_NUMBER";

//Ads
export const SET_ADS_LAST_ID = "SET_ADS_LAST_ID";
export const ADS_ADD_BLACK_LIST_ID = "ADS_ADD_BLACK_LIST_ID";
export const ADS_CLEAR_BLACK_LIST_IDS = "ADS_CLEAR_BLACK_LIST_IDS";
export const ADS_ADD_ID = "ADS_ADD_ID";
export const ADS_ADD_BLACK_AND_WHITE_ID = "ADS_ADD_BLACK_AND_WHITE_ID";
