/**
 * this files conatis Types of Actions that we used in Redux
 */

//Clinet Sorting
export const SORT_BY_SIZE_CLIENT_ASC = "SORT_BY_SIZE_CLIENT_ASC";
export const SORT_BY_SIZE_CLIENT_DESC = "SORT_BY_SIZE_CLIENT_DESC";
export const SORT_BY_PRICE_CLIENT_ASC = "SORT_BY_PRICE_CLIENT_ASC";
export const SORT_BY_PRICE_CLIENT_DESC = "SORT_BY_PRICE_CLIENT_DESC";
export const SORT_BY_ID_CLIENT_ASC = "SORT_BY_ID_CLIENT_ASC";
export const SORT_BY_ID_CLIENT_DESC = "SORT_BY_ID_CLIENT_DESC";
export const SORT_BY_NO_SORT = "SORT_BY_NO_SORT";
//Server Sorting
export const SORT_BY_SIZE_SERVER = "SORT_BY_SIZE_SERVER";
export const SORT_BY_PRICE_SERVER = "SORT_BY_PRICE_SERVER";
export const SORT_BY_ID_SERVER = "SORT_BY_ID_SERVER";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";

export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const PRODUCTS_ACTIVE_IN_ACTIVES = "PRODUCTS_ACTIVE_IN_ACTIVES";
export const PRODUCTS_END_OF_PRODUCTS = "PRODUCTS_END_OF_PRODUCTS";
export const PRODUCTS_SET_BATCH = "PRODUCTS_SET_BATCH";
export const PRODUCTS_ADD_BATCH = "PRODUCTS_ADD_BATCH";

export const SET_PAGINATION_PAGE_NUMBER = "SET_PAGINATION_PAGE_NUMBER";
export const INCREASE_PAGINATION_PAGE_NUMBER =
  "INCREASE_PAGINATION_PAGE_NUMBER";
