/**
 * this files conatis Types of Actions that we used in Redux
 */

//Clinet Sorting
export const SORT_BY_SIZE_CLIENT_ASC = "SORT_BY_SIZE_CLIENT_ASC";
export const SORT_BY_SIZE_CLIENT_DESC = "SORT_BY_SIZE_CLIENT_DESC";
export const SORT_BY_PRICE_CLIENT_ASC = "SORT_BY_PRICE_CLIENT_ASC";
export const SORT_BY_PRICE_CLIENT_DESC = "SORT_BY_PRICE_CLIENT_DESC";
export const SORT_BY_ID_CLIENT_ASC = "SORT_BY_ID_CLIENT_ASC";
export const SORT_BY_ID_CLIENT_DESC = "SORT_BY_ID_CLIENT_DESC";

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const PRODUCTS_ACTIVE_IN_ACTIVES = "PRODUCTS_ACTIVE_IN_ACTIVES";
export const PRODUCTS_NO_PRODUCTS = "PRODUCTS_NO_PRODUCTS";
